import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { supabase } from '../lib/supabase';

const Certificate = () => {
  const { t } = useTranslation();
  const { id } = useParams();
  const navigate = useNavigate();
  
  const [certificateData, setCertificateData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const loadCertificateData = async () => {
      if (!id) {
        setError(t('certificate.noId'));
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        
        // Parse certificate ID to extract user ID and timestamp
        // Expected format: CERT-userId-timestamp
        const certParts = id.split('-');
        if (certParts.length !== 3 || certParts[0] !== 'CERT') {
          setError(t('certificate.invalidId'));
          setLoading(false);
          return;
        }

        const userId = certParts[1];
        const timestamp = parseInt(certParts[2]);

        // Validate timestamp (should be within reasonable range)
        const now = Date.now();
        const maxAge = 365 * 24 * 60 * 60 * 1000; // 1 year
        if (now - timestamp > maxAge) {
          setError(t('certificate.expired'));
          setLoading(false);
          return;
        }

        // Get user profile data
        const { data: profile, error: profileError } = await supabase
          .from('profiles')
          .select('name, email, created_at')
          .eq('id', userId)
          .single();

        if (profileError) {
          console.error('Error loading profile:', profileError);
          setError(t('certificate.profileNotFound'));
          setLoading(false);
          return;
        }

        // Get user gamification data
        const { data: gamification, error: gamificationError } = await supabase
          .from('user_gamification')
          .select('total_xp, level, badges')
          .eq('user_id', userId)
          .single();

        if (gamificationError) {
          console.error('Error loading gamification:', gamificationError);
          // Continue with profile data even if gamification data is missing
        }

        // Get completed lessons count
        const { data: lessons, error: lessonsError } = await supabase
          .from('user_progress')
          .select('lesson_id')
          .eq('user_id', userId)
          .eq('completed', true);

        if (lessonsError) {
          console.error('Error loading lessons:', lessonsError);
        }

        const certificateInfo = {
          id,
          studentName: profile.name || profile.email.split('@')[0] || 'Student',
          email: profile.email,
          issueDate: new Date(timestamp).toLocaleDateString(),
          totalXP: gamification?.total_xp || 0,
          level: gamification?.level || 1,
          badges: gamification?.badges || [],
          completedLessons: lessons?.length || 0,
          memberSince: new Date(profile.created_at).toLocaleDateString()
        };

        setCertificateData(certificateInfo);
      } catch (err) {
        console.error('Unexpected error loading certificate:', err);
        setError(t('certificate.loadError'));
      } finally {
        setLoading(false);
      }
    };

    loadCertificateData();
  }, [id, t]);

  const handleDownload = () => {
    if (!certificateData) return;

    // Create a simple text-based certificate download
    const certificateText = `
CERTIFICATE OF COMPLETION

This is to certify that
${certificateData.studentName}
has successfully completed the Dao-Yu-101 learning program.

Achievements:
- Total XP: ${certificateData.totalXP.toLocaleString()}
- Level: ${certificateData.level}
- Completed Lessons: ${certificateData.completedLessons}
- Badges Earned: ${certificateData.badges.length}

Certificate ID: ${certificateData.id}
Issue Date: ${certificateData.issueDate}
Member Since: ${certificateData.memberSince}

This certificate was generated by Dao-Yu-101 Learning Platform.
    `.trim();

    // Create and download text file
    const blob = new Blob([certificateText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${certificateData.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: 'var(--color-bg)' }}>
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mx-auto mb-4"></div>
          <p style={{ color: 'var(--color-text)' }}>{t('common.loading')}</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center p-6" style={{ backgroundColor: 'var(--color-bg)' }}>
        <div className="max-w-md text-center">
          <div className="text-red-500 text-6xl mb-4">🚫</div>
          <h2 className="text-2xl font-bold mb-2" style={{ color: 'var(--color-text)' }}>
            {t('certificate.error')}
          </h2>
          <p style={{ color: 'var(--color-text-muted)' }} className="mb-6">
            {error}
          </p>
          <button
            onClick={() => navigate('/')}
            className="px-6 py-3 rounded font-medium text-white"
            style={{ backgroundColor: 'var(--color-primary)' }}
          >
            {t('certificate.backToHome')}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-6" style={{ backgroundColor: 'var(--color-bg)' }}>
      <div className="max-w-4xl mx-auto">
        {/* Certificate Container */}
        <div className="rounded-lg shadow-2xl overflow-hidden" style={{ backgroundColor: 'var(--color-surface)' }}>
          {/* Certificate Header */}
          <div className="text-center p-8 border-b-4" style={{ borderColor: 'var(--color-primary)' }}>
            <h1 className="text-4xl font-bold mb-2" style={{ color: 'var(--color-primary)' }}>
              🏆 {t('certificate.title')}
            </h1>
            <p className="text-lg" style={{ color: 'var(--color-text-muted)' }}>
              {t('certificate.subtitle')}
            </p>
          </div>

          {/* Certificate Body */}
          <div className="p-8">
            {/* Student Information */}
            <div className="text-center mb-8">
              <p className="text-lg mb-2" style={{ color: 'var(--color-text)' }}>
                {t('certificate.thisIsToCertify')}
              </p>
              <h2 className="text-3xl font-bold mb-4" style={{ color: 'var(--color-text)' }}>
                {certificateData.studentName}
              </h2>
              <p className="text-lg" style={{ color: 'var(--color-text-muted)' }}>
                {t('certificate.hasCompleted')}
              </p>
            </div>

            {/* Achievements Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
              <div className="text-center p-6 rounded" style={{ backgroundColor: 'var(--color-bg)' }}>
                <div className="text-3xl font-bold mb-2" style={{ color: 'var(--color-primary)' }}>
                  {certificateData.totalXP.toLocaleString()}
                </div>
                <div style={{ color: 'var(--color-text-muted)' }}>
                  {t('certificate.totalXP')}
                </div>
              </div>
              <div className="text-center p-6 rounded" style={{ backgroundColor: 'var(--color-bg)' }}>
                <div className="text-3xl font-bold mb-2" style={{ color: 'var(--color-primary)' }}>
                  {certificateData.level}
                </div>
                <div style={{ color: 'var(--color-text-muted)' }}>
                  {t('certificate.level')}
                </div>
              </div>
              <div className="text-center p-6 rounded" style={{ backgroundColor: 'var(--color-bg)' }}>
                <div className="text-3xl font-bold mb-2" style={{ color: 'var(--color-primary)' }}>
                  {certificateData.completedLessons}
                </div>
                <div style={{ color: 'var(--color-text-muted)' }}>
                  {t('certificate.completedLessons')}
                </div>
              </div>
              <div className="text-center p-6 rounded" style={{ backgroundColor: 'var(--color-bg)' }}>
                <div className="text-3xl font-bold mb-2" style={{ color: 'var(--color-primary)' }}>
                  {certificateData.badges.length}
                </div>
                <div style={{ color: 'var(--color-text-muted)' }}>
                  {t('certificate.badges')}
                </div>
              </div>
            </div>

            {/* Badges Display */}
            {certificateData.badges.length > 0 && (
              <div className="mb-8">
                <h3 className="text-xl font-bold mb-4 text-center" style={{ color: 'var(--color-text)' }}>
                  {t('certificate.earnedBadges')}
                </h3>
                <div className="flex flex-wrap justify-center gap-4">
                  {certificateData.badges.map((badge, index) => (
                    <div
                      key={index}
                      className="px-4 py-2 rounded-full text-sm font-medium"
                      style={{
                        backgroundColor: 'var(--color-primary)',
                        color: 'white'
                      }}
                    >
                      {badge === 'First Steps' && '🎯 '}
                      {badge === 'Quiz Master' && '🏆 '}
                      {badge === 'On Fire' && '🔥 '}
                      {t(`badges.${badge.toLowerCase().replace(' ', '')}`)}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Certificate Details */}
            <div className="border-t pt-6" style={{ borderColor: 'var(--color-border)' }}>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                <div>
                  <span style={{ color: 'var(--color-text-muted)' }}>
                    {t('certificate.certificateId')}:
                  </span>
                  <div className="font-mono" style={{ color: 'var(--color-text)' }}>
                    {certificateData.id}
                  </div>
                </div>
                <div>
                  <span style={{ color: 'var(--color-text-muted)' }}>
                    {t('certificate.issueDate')}:
                  </span>
                  <div style={{ color: 'var(--color-text)' }}>
                    {certificateData.issueDate}
                  </div>
                </div>
                <div>
                  <span style={{ color: 'var(--color-text-muted)' }}>
                    {t('certificate.memberSince')}:
                  </span>
                  <div style={{ color: 'var(--color-text)' }}>
                    {certificateData.memberSince}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Certificate Footer */}
          <div className="bg-gray-50 p-6 border-t" style={{ borderColor: 'var(--color-border)' }}>
            <div className="text-center">
              <p className="text-sm mb-4" style={{ color: 'var(--color-text-muted)' }}>
                {t('certificate.verificationNote')}
              </p>
              <div className="flex justify-center space-x-4">
                <button
                  onClick={handleDownload}
                  className="px-6 py-3 rounded font-medium text-white"
                  style={{ backgroundColor: 'var(--color-primary)' }}
                >
                  {t('certificate.download')}
                </button>
                <button
                  onClick={() => navigate('/')}
                  className="px-6 py-3 rounded font-medium"
                  style={{
                    backgroundColor: 'var(--color-bg)',
                    color: 'var(--color-text)',
                    border: `1px solid var(--color-border)`
                  }}
                >
                  {t('certificate.backToHome')}
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Verification Info */}
        <div className="mt-8 text-center">
          <p className="text-sm" style={{ color: 'var(--color-text-muted)' }}>
            {t('certificate.verificationInfo')}
          </p>
        </div>
      </div>
    </div>
  );
};

export default Certificate;
